// Vue 3 (composition and SFC)/src/components/LabeledNumberInput.vue
<script setup>
const emit = defineEmits(['value']);

const props = defineProps({
  labelText: {
    type: String,
    required: true
  },
  value: {
    type: Number,
    required: true
  }
});

function handleChange(e) {
  const valueNumber = Number(e.target.value); // string to number
  emit('value', valueNumber);
}
</script>

<template>
  <label class="display-block padding border-bottom">
    {{ labelText }}
    <input type="number" :value="value" @change.self.prevent="handleChange" class="margin-only-left-1 input-number" />
  </label>
</template>

// React/classes/src/components/LabeledNumberInput.js
import React from "react";

class LabeledNumberInput extends React.Component {
  constructor(props) {
    super(props);

    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(e) {
    e.preventDefault();

    const valueNumber = Number(e.target.value); // string to number
    this.props.onChange(valueNumber);
  }

  render() {
    return (
      <label className="display-block padding border-bottom">
        {this.props.labelText}
        <input
          type="number"
          value={this.props.value}
          onChange={this.handleChange}
          className="margin-only-left-1 input-number"
        />
      </label>
    );
  }
}

export default LabeledNumberInput;
