// Lit/src/components/LabeledNumberInput.js
import {LitElement, html} from 'lit';
import dispatchEventValue from '../helpers/customEvent.helpers.js';
import style from '../style.js';

export class LabeledNumberInput extends LitElement {
  static styles = [style];

  static get properties() {
    return {
      labelText: {type: String},
      value: {type: Number},
    };
  }

  _handleChange(e) {
    // e.preventDefault(); // TODO: is needed?
    dispatchEventValue(this, e.target.value);
  }

  render() {
    return html`
      <label class="display-block padding border-bottom">
        ${this.labelText}
        <input
          type="number"
          @input=${this._handleChange}
          .value=${this.value}
          class="margin-only-left-1 input-number"
        />
      </label>
    `;
  }
}

window.customElements.define('labeled-number-input', LabeledNumberInput);

// React/classes/src/components/LabeledNumberInput.js
import React from "react";

class LabeledNumberInput extends React.Component {
  constructor(props) {
    super(props);

    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(e) {
    e.preventDefault();

    const valueNumber = Number(e.target.value); // string to number
    this.props.onChange(valueNumber);
  }

  render() {
    return (
      <label className="display-block padding border-bottom">
        {this.props.labelText}
        <input
          type="number"
          value={this.props.value}
          onChange={this.handleChange}
          className="margin-only-left-1 input-number"
        />
      </label>
    );
  }
}

export default LabeledNumberInput;
