// Svelte/src/lib/components/RadioGroup.svelte
<script>
  export let textValueCombinations;
  export let value;

  $: name = getName(textValueCombinations);

  function getName(textValueCombinations) {
    let name = textValueCombinations?.[0]?.value;

    for (let i = 1; i < textValueCombinations?.length; i++) {
      name += `, ${textValueCombinations[i].value}`;
    }

    return name;
  }
</script>

<div>
  {#each textValueCombinations as combination}
    <label class="display-block">
      <!-- on:change|preventDefault is not needed -->
      <input
        class="input-radio"
        type="radio"
        bind:group={value}
        {name}
        value={combination.value}
      />
      {combination.text}
    </label>
  {/each}
</div>

// React/classes/src/components/RadioGroup.js
import React from "react";

class RadioGroup extends React.Component {
  constructor(props) {
    super(props);

    this.handleChange = this.handleChange.bind(this);
  }

  getName() {
    let name = this.props.textValueCombinations?.[0]?.value;

    for (let i = 1; i < this.props.textValueCombinations?.length; i++) {
      name += `, ${this.props.textValueCombinations[i].value}`;
    }

    return name;
  }

  handleChange(e) {
    // e.preventDefault(); is not needed

    this.props.onChange(e.target.value);
  }

  render() {
    const labeledRadioInputs = this.props.textValueCombinations.map((x, i) => (
      <label className="display-block" key={i}>
        <input
          type="radio"
          name={this.getName()}
          value={x.value}
          onChange={this.handleChange}
          defaultChecked={x.value === this.props.value} // the attribute defaultChecked should be used and not the attribute checked
          className="input-radio"
        />
        {x.text}
      </label>
    ));

    return <div>{labeledRadioInputs}</div>;
  }
}

export default RadioGroup;
