// Solid 1/src/components/TextSelect.jsx
import { For } from 'solid-js';

export default function TextSelect(props) {
  let selectClassName = "select";
  if (props.className) {
    selectClassName += ` ${props.className}`;
  }

  return (
    <select value={props.value} class={selectClassName} onChange={e => props.onChange(e.target.value)}>
      <For each={props.values}>{value =>
        <option value={value}>
          {value}
        </option>
      }</For>
    </select>
  );
}

// React/classes/src/components/TextSelect.js
import React from "react";

class TextSelect extends React.Component {
  constructor(props) {
    super(props);

    this.className = "select";

    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(e) {
    e.preventDefault();

    this.props.onChange(e.target.value);
  }

  render() {
    let selectClassName = this.className;
    if (this.props.className) {
      selectClassName += ` ${this.props.className}`;
    }

    const options = this.props.values.map((x) => (
      <option key={x} value={x}>
        {x}
      </option>
    ));

    return (
      <select
        value={this.props.value}
        onChange={this.handleChange}
        className={selectClassName}
      >
        {options}
      </select>
    );
  }
}

export default TextSelect;
