// React/music-calculators/src/components/LabeledNumberInput.js
import React from "react";

class LabeledNumberInput extends React.Component {
  constructor(props) {
    super(props);

    this.value = this.props.value ? this.props.value : 0;

    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(e) {
    e.preventDefault();

    this.value = e.target.value;
    this.props.onChange(this.value);
  }

  render() {
    return (
      <label className={"display-block padding border-bottom"}>
        {this.props.labelText}
        <input
          type="number"
          value={this.value}
          onChange={this.handleChange}
          class="margin-only-left-1 input-number"
        />
      </label>
    );
  }
}

export default LabeledNumberInput;

// Vue 3 (composition and SFC)/src/components/LabeledNumberInput.vue
<script setup>
const emit = defineEmits(['value']);

const props = defineProps({
  labelText: {
    type: String,
    required: true
  },
  value: {
    type: String,
    required: true
  }
});

function handleChange(e) {
  emit('value', e.target.value);
}
</script>

<template>
  <label class="display-block padding border-bottom">
    {{ labelText }}
    <input type="number" :value="value" @change.self.prevent="handleChange" class="margin-only-left-1 input-number" />
  </label>
</template>
