// React/classes/src/components/LabeledTextSelect.js
import React from "react";
import TextSelect from "./TextSelect.js";

class LabeledTextSelect extends React.Component {
  constructor(props) {
    super(props);

    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(value) {
    this.props.onChange(value);
  }

  render() {
    return (
      <label className={this.props.className}>
        {this.props.labelText}
        <TextSelect
          values={this.props.values}
          value={this.props.value}
          onChange={this.handleChange}
        />
      </label>
    );
  }
}

export default LabeledTextSelect;

// Vue 3 (composition and SFC)/src/components/LabeledTextSelect.vue
<script setup>
import TextSelect from './TextSelect.vue';

const emit = defineEmits(['value']);

const props = defineProps({
  labelText: {
    type: String,
    required: true
  },
  value: {
    type: String,
    required: true
  },
  values: {
    type: Array,
    required: true
  },
  className: {
    type: String,
    required: false
  }
});

function handleChange(e) {
  emit('value', e);
}
</script>

<template>
  <label :class="className">
    {{ labelText }}
    <TextSelect :values="values" :value="value" @value="handleChange" />
  </label>
</template>
