// Svelte/src/lib/components/LabeledRadioGroup.svelte
<script>
  import RadioGroup from "./RadioGroup.svelte";

  export let labelText;
  export let textValueCombinations;
  export let value;
</script>

<div class="display-block padding border-bottom">
  <p class="text-before-list">{labelText}</p>
  <RadioGroup {textValueCombinations} bind:value />
</div>

// Vue 3 (composition and SFC)/src/components/LabeledRadioGroup.vue
<script setup>
import RadioGroup from './RadioGroup.vue';

const emit = defineEmits(['value']);

const props = defineProps({
  labelText: {
    type: String,
    required: true
  },
  value: {
    type: String,
    required: true
  },
  textValueCombinations: {
    type: Array,
    required: true
  }
});

function handleChange(e) {
  emit('value', e);
}
</script>

<template>
  <div className="display-block padding border-bottom">
    <p className="text-before-list">{{ props.labelText }}</p>
    <RadioGroup :textValueCombinations="textValueCombinations" :value="value" @value="handleChange" />
  </div>
</template>
