// Svelte/music-calculators/src/lib/components/RadioGroup.svelte
<script>
  export let textValueCombinations;
  export let value;

  let name = "";
  const length = textValueCombinations.length;

  if (length > 0) {
    name = textValueCombinations[0].value;
  }

  if (length > 1) {
    for (let i = 1; i < length; i++) {
      name += `, ${textValueCombinations[i].value}`;
    }
  }
</script>

{#each textValueCombinations as combination}
  <label class="display-block">
    <input
      class="input-radio"
      type="radio"
      bind:group={value}
      {name}
      value={combination.value}
    />
    {combination.text}
  </label>
{/each}

// Vue 3 (composition and SFC)/src/components/RadioGroup.vue
<script setup>
import { computed } from 'vue';

const props = defineProps({
  textValueCombinations: {
    type: Array,
    required: true
  },
  value: {
    type: String,
    required: true
  }
});

const name = computed(() => {
  let name = props.textValueCombinations?.[0]?.value;

  for (let i = 1; i < props.textValueCombinations?.length; i++) {
    name += `, ${props.textValueCombinations[i].value}`;
  }

  return name;
});

</script>

<!-- TODO: whole component is not completed -->
<template>
  <label v-for="combination in textValueCombinations" :key="combination.value" class="display-block">
    <input type="radio" :name="name" :value="combination.value" class="input-radio" />
    {{ combination.value }}
  </label>
</template>
