// Svelte/src/lib/components/ReverbCalculator.svelte
<script>
  import arithmeticOperation from "../constants/arithmeticOperation.constants.js";
  import reverb from "../constants/reverb.constants.js";
  import MusicCalculator from "./MusicCalculator.svelte";

  export let calculatorOperation;
  export let tempo;
  export let valueOne;
  export let valueTwo;
  export let subtractionText;

  const preDelay = addParentheses(reverb.preDelay);
  const decay = addParentheses(reverb.decay);
  const totalReverb = addParentheses(reverb.totalReverb);

  $: labeledFormula = getLabeledFormula(
    calculatorOperation,
    valueOne,
    valueTwo,
    subtractionText
  );

  function getLabeledFormula(
    calculatorOperation,
    valueOne,
    valueTwo,
    subtractionText
  ) {
    const labeledFormula = {
      operator: calculatorOperation,
      operandLabelCombinations: [
        { operand: valueOne, label: preDelay },
        { operand: valueTwo, label: decay },
      ],
      label: totalReverb,
    };

    if (calculatorOperation === arithmeticOperation.subtraction) {
      labeledFormula.operandLabelCombinations[0].label = totalReverb;

      if (subtractionText === reverb.preDelay) {
        labeledFormula.operandLabelCombinations[1].label = preDelay;
        labeledFormula.label = decay;
      } else {
        labeledFormula.operandLabelCombinations[1].label = decay;
        labeledFormula.label = preDelay;
      }
    }

    return labeledFormula;
  }

  function addParentheses(string) {
    return `(${string})`;
  }
</script>

<MusicCalculator {tempo} {labeledFormula} />

// Vue 3 (composition and SFC)/src/components/ReverbCalculator.vue
<script setup>
import arithmeticOperation from '../constants/arithmeticOperation.constants.js';
import reverb from '../constants/reverb.constants.js';
import MusicCalculator from './MusicCalculator.vue';

const props = defineProps({
  calculatorOperation: {
    type: String,
    required: true
  },
  tempo: {
    type: Number,
    required: true
  },
  valueOne: {
    type: String,
    required: true
  },
  valueTwo: {
    type: String,
    required: true
  },
  subtractionText: {
    type: String,
    required: true
  }
});

const preDelay = addParentheses(reverb.preDelay);
const decay = addParentheses(reverb.decay);
const totalReverb = addParentheses(reverb.totalReverb);

function addParentheses(string) {
  return `(${string})`;
}

function getLabeledFormula() {
  const labeledFormula = {
    operator: props.calculatorOperation,
    operandLabelCombinations: [
      { operand: props.valueOne, label: preDelay },
      { operand: props.valueTwo, label: decay },
    ],
    label: totalReverb,
  };

  if (props.calculatorOperation === arithmeticOperation.subtraction) {
    labeledFormula.operandLabelCombinations[0].label = totalReverb;

    if (props.subtractionText === reverb.preDelay) {
      labeledFormula.operandLabelCombinations[1].label = preDelay;
      labeledFormula.label = decay;
    } else {
      labeledFormula.operandLabelCombinations[1].label = decay;
      labeledFormula.label = preDelay;
    }
  }

  return labeledFormula;
}
</script>

<template>
  <MusicCalculator :tempo="tempo" :labeledFormula="getLabeledFormula()" />
</template>
