// React/classes/src/components/TextSelect.js
import React from "react";

class TextSelect extends React.Component {
  constructor(props) {
    super(props);

    this.className = "select";

    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(e) {
    e.preventDefault();

    this.props.onChange(e.target.value);
  }

  render() {
    let selectClassName = this.className;
    if (this.props.className) {
      selectClassName += ` ${this.props.className}`;
    }

    const options = this.props.values.map((x) => (
      <option key={x} value={x}>
        {x}
      </option>
    ));

    return (
      <select
        value={this.props.value}
        onChange={this.handleChange}
        className={selectClassName}
      >
        {options}
      </select>
    );
  }
}

export default TextSelect;

// Vue 3 (composition and SFC)/src/components/TextSelect.vue
<script setup>
import { computed } from 'vue';

const emit = defineEmits(['value']);

const props = defineProps({
  value: {
    type: String,
    required: true
  },
  values: {
    type: Array,
    required: true
  },
  className: {
    type: String,
    required: false
  }
});

const selectClassName = computed(() => {
  let result = "select";

  if (props.className) {
    result += ` ${props.className}`;
  }

  return result;
});

function handleChange(e) {
  emit('value', e.target.value);
}
</script>

<template>
  <select :value="value" @change.self.prevent="handleChange" :class="selectClassName">
    <option v-for="value in values" :key="value">{{ value }}</option>
  </select>
</template>
