// React/classes/src/components/ReverbCalculator.js
import React from "react";
import arithmeticOperation from "../constants/arithmeticOperation.constants.js";
import reverb from "../constants/reverb.constants.js";
import MusicCalculator from "./MusicCalculator.js";

class ReverbCalculator extends React.Component {
  constructor(props) {
    super(props);

    this.preDelay = this.addParentheses(reverb.preDelay);
    this.decay = this.addParentheses(reverb.decay);
    this.totalReverb = this.addParentheses(reverb.totalReverb);
  }

  addParentheses(string) {
    return `(${string})`;
  }

  render() {
    const labeledFormula = {
      operator: this.props.calculatorOperation,
      operandLabelCombinations: [
        { operand: this.props.valueOne, label: this.preDelay },
        { operand: this.props.valueTwo, label: this.decay },
      ],
      label: this.totalReverb,
    };

    if (this.props.calculatorOperation === arithmeticOperation.subtraction) {
      labeledFormula.operandLabelCombinations[0].label = this.totalReverb;

      if (this.props.subtractionText === reverb.preDelay) {
        labeledFormula.operandLabelCombinations[1].label = this.preDelay;
        labeledFormula.label = this.decay;
      } else {
        labeledFormula.operandLabelCombinations[1].label = this.decay;
        labeledFormula.label = this.preDelay;
      }
    }

    return (
      <MusicCalculator
        tempo={this.props.tempo}
        labeledFormula={labeledFormula}
      />
    );
  }
}

export default ReverbCalculator;

// Svelte/src/lib/components/ReverbCalculator.svelte
<script>
  import arithmeticOperation from "../constants/arithmeticOperation.constants.js";
  import reverb from "../constants/reverb.constants.js";

  import MusicCalculator from "./MusicCalculator.svelte";

  export let calculatorOperation;
  export let tempo;
  export let valueOne;
  export let valueTwo;
  export let subtractionText;

  const preDelay = addParentheses(reverb.preDelay);
  const decay = addParentheses(reverb.decay);
  const totalReverb = addParentheses(reverb.totalReverb);

  let labeledFormula = {};

  $: setCalculatorValues(
    calculatorOperation,
    valueOne,
    valueTwo,
    subtractionText
  );

  function setCalculatorValues(
    calculatorOperation,
    valueOne,
    valueTwo,
    subtractionText
  ) {
    labeledFormula = {
      operator: calculatorOperation,
      operandLabelCombinations: [
        { operand: valueOne, label: preDelay },
        { operand: valueTwo, label: decay },
      ],
      label: totalReverb,
    };

    if (calculatorOperation === arithmeticOperation.subtraction) {
      labeledFormula.operandLabelCombinations[0].label = totalReverb;

      if (subtractionText === reverb.preDelay) {
        labeledFormula.operandLabelCombinations[1].label = preDelay;
        labeledFormula.label = decay;
      } else {
        labeledFormula.operandLabelCombinations[1].label = decay;
        labeledFormula.label = preDelay;
      }
    }
  }

  function addParentheses(string) {
    return `(${string})`;
  }
</script>

<MusicCalculator {tempo} {labeledFormula} />
