// Vue 3 (composition and SFC)/src/App.vue
<script setup>
// import HelloWorld from './components/HelloWorld.vue'
// import TheWelcome from './components/TheWelcome.vue'
import style from "./style.js";

import ReverbCalculatorApp from './components/ReverbCalculatorApp.vue'

// If there is a shadow dom, the style element gets appended outside of it.
var element = document.createElement("style");
element.innerHTML = style;
document.body.appendChild(element);
</script>

<template>
  <!-- <header> -->
  <!-- <img alt="Vue logo" class="logo" src="./assets/logo.svg" width="125" height="125" /> -->

  <!-- <div class="wrapper"> -->
  <!-- <HelloWorld msg="You did it!" /> -->
  <!-- </div> -->
  <!-- </header> -->

  <main>
    <!-- <TheWelcome /> -->
    <ReverbCalculatorApp />
  </main>
</template>

<style scoped>
header {
  line-height: 1.5;
}

.logo {
  display: block;
  margin: 0 auto 2rem;
}

@media (min-width: 1024px) {
  header {
    display: flex;
    place-items: center;
    padding-right: calc(var(--section-gap) / 2);
  }

  .logo {
    margin: 0 2rem 0 0;
  }

  header .wrapper {
    display: flex;
    place-items: flex-start;
    flex-wrap: wrap;
  }
}
</style>

// Svelte/music-calculators/src/App.svelte
<script>
  import svelteLogo from "./assets/svelte.svg";

  import style from "./lib/style.js";

  import Counter from "./lib/Counter.svelte";

  import ReverbCalculatorApp from "./lib/components/ReverbCalculatorApp.svelte";

  // If there is a shadow dom, the style element gets appended outside of it.
  var element = document.createElement("style");
  element.innerHTML = style;
  document.body.appendChild(element);
</script>

<main>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>
  <h1>Vite + Svelte</h1>

  <div class="card">
    <Counter />
  </div>

  <!-- Faking the HTML <body> tag. -->
  <div id="body">
    <ReverbCalculatorApp />
  </div>

  <p>
    Check out <a href="https://github.com/sveltejs/kit#readme" target="_blank"
      >SvelteKit</a
    >, the official Svelte app framework powered by Vite!
  </p>

  <p class="read-the-docs">Click on the Vite and Svelte logos to learn more</p>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
  .read-the-docs {
    color: #888;
  }
</style>
