// React/music-calculators/src/components/ReverbCalculator.js
import React from "react";

import arithmeticOperation from "../constants/arithmeticOperation.constants.js";
import reverb from "../constants/reverb.constants.js";

import Calculator from "./Calculator.js";

class ReverbCalculator extends React.Component {
  constructor(props) {
    super(props);

    this.preDelay = this.addParentheses(reverb.preDelay);
    this.decay = this.addParentheses(reverb.decay);
    this.totalReverb = this.addParentheses(reverb.totalReverb);
  }

  addParentheses(string) {
    return `(${string})`;
  }

  render() {
    if (
      !this.props.arithmeticOperation ||
      !this.props.tempo ||
      !this.props.valueOne ||
      !this.props.valueTwo ||
      (this.props.arithmeticOperation === arithmeticOperation.subtraction &&
        !this.props.subtractionText)
    ) {
      return;
    }

    let valueOneText = this.preDelay;
    let valueTwoText = this.decay;
    let resultTextPart = this.totalReverb;

    if (this.props.arithmeticOperation === arithmeticOperation.subtraction) {
      valueOneText = this.totalReverb;

      if (this.props.subtractionText === reverb.preDelay) {
        valueTwoText = this.preDelay;
        resultTextPart = this.decay;
      } else {
        valueTwoText = this.decay;
        resultTextPart = this.preDelay;
      }
    }

    return (
      <Calculator
        tempo={this.props.tempo}
        valueOne={this.props.valueOne}
        valueTwo={this.props.valueTwo}
        valueOneText={valueOneText}
        valueTwoText={valueTwoText}
        resultTextPart={resultTextPart}
        arithmeticOperation={this.props.arithmeticOperation}
      />
    );
  }
}

export default ReverbCalculator;

// Svelte/music-calculators/src/lib/components/ReverbCalculator.svelte
<script>
  import arithmeticOperation from "../constants/arithmeticOperation.constants.js";
  import reverb from "../constants/reverb.constants.js";

  import Calculator from "./Calculator.svelte";

  export let calculatorOperation;
  export let tempo;
  export let valueOne;
  export let valueTwo;
  export let subtractionText;

  const preDelay = addParentheses(reverb.preDelay);
  const decay = addParentheses(reverb.decay);
  const totalReverb = addParentheses(reverb.totalReverb);

  let valueOneText = preDelay;
  let valueTwoText = decay;
  let resultTextPart = totalReverb;

  $: setCalculatorValues(calculatorOperation, subtractionText);

  function setCalculatorValues(calculatorOperation, subtractionText) {
    if (calculatorOperation === arithmeticOperation.subtraction) {
      valueOneText = totalReverb;

      if (subtractionText === reverb.preDelay) {
        valueTwoText = preDelay;
        resultTextPart = decay;
      } else {
        valueTwoText = decay;
        resultTextPart = preDelay;
      }
    }
  }

  function addParentheses(string) {
    return `(${string})`;
  }
</script>

<Calculator
  {tempo}
  {valueOne}
  {valueTwo}
  {valueOneText}
  {valueTwoText}
  {resultTextPart}
  {calculatorOperation}
/>
