// Vue 3 (composition and SFC)/src/components/ReverbCalculatorApp.vue
<script setup>
import arithmeticOperation from '../constants/arithmeticOperation.constants.js';
import durations from '../constants/durations.constants.js';
import reverb from '../constants/reverb.constants.js';
import LabeledNumberInput from './LabeledNumberInput.vue';
import LabeledRadioGroup from './LabeledRadioGroup.vue';
import LabeledTextSelect from './LabeledTextSelect.vue';
import TextSelect from './TextSelect.vue';

const preDelayColon = addColon(reverb.preDelay);
const decayColon = addColon(reverb.decay);
const totalReverbColon = addColon(reverb.totalReverb);

const values = [preDelayColon, decayColon];
const textValueCombinations = [
  {
    text: 'The total reverb duration by choosing a duration for the pre-delay and decay',
    value: arithmeticOperation.addition,
  },
  {
    text: 'The pre-delay or decay duration by choosing a duration for the total reverb, and pre-delay or decay',
    value: arithmeticOperation.subtraction,
  },
];

const defaultValueSelect = '1/64 note';

const subtractionTextColon = preDelayColon;
const valueOne = defaultValueSelect;
const valueTwo = defaultValueSelect;
const durationResult = textValueCombinations[0].value;
const tempo = 128;

const child1MarginOnlyLeft = "child-1-margin-only-left-1";
const marginOnlyLeft = "margin-only-left-1";

function addColon(string) {
  return `${string}:`;
}

function handleChangeTempo(e) {
  tempo = e;
}

function handleChangeDurationResult(e) {
  durationResult = e;
}

function handleChangeValueOne(e) {
  valueOne = e.detail;
}

function handleChangeValueTwo(e) {
  valueTwo = e.detail;
}
</script>

<template>
  <LabeledNumberInput labelText="Tempo in BPM:" :value="tempo" @value="handleChangeTempo" />
  <LabeledRadioGroup labelText="Calculate in ms:" :textValueCombinations="textValueCombinations" :value="durationResult"
    @value="handleChangeDurationResult" class="display-block padding border-bottom" />
  <div class="display-flex align-items-center padding border-bottom">
    <template v-if="durationResult === arithmeticOperation.addition">
      <LabeledTextSelect :labelText="preDelayColon" :values="durations" :value="valueOne" @value="handleChangeValueOne"
        :className="child1MarginOnlyLeft" />
      <p :class="marginOnlyLeft">+</p>
      <LabeledTextSelect :labelText="decayColon" :values="durations" :value="valueTwo" @value="handleChangeValueTwo"
        :class="`${child1MarginOnlyLeft} ${marginOnlyLeft}`" />
    </template>
    <template v-else>
      <p :class="marginOnlyLeft">-</p>
    </template>
  </div>
</template>

// Svelte/music-calculators/src/lib/components/ReverbCalculatorApp.svelte
<script>
  import arithmeticOperation from "../constants/arithmeticOperation.constants.js";
  import durations from "../constants/durations.constants.js";
  import reverb from "../constants/reverb.constants.js";

  import OptionalLabeledTextSelect from "./OptionalLabeledTextSelect.svelte";
  import LabeledNumberInput from "./LabeledNumberInput.svelte";
  import LabeledRadioGroup from "./LabeledRadioGroup.svelte";
  import ReverbCalculator from "./ReverbCalculator.svelte";

  const preDelayColon = addColon(reverb.preDelay);
  const decayColon = addColon(reverb.decay);
  const totalReverbColon = addColon(reverb.totalReverb);

  const values = [preDelayColon, decayColon];

  const textValueCombinations = [
    {
      text: "The total reverb duration by choosing a duration for the pre-delay and decay",
      value: arithmeticOperation.addition,
    },
    {
      text: "The pre-delay or decay duration by choosing a duration for the total reverb, and pre-delay or decay",
      value: arithmeticOperation.subtraction,
    },
  ];

  const defaultValueSelect = "1/64 note";

  let tempo = 128;
  let durationResult = textValueCombinations[0].value;
  let valueOne = defaultValueSelect;
  let valueTwo = defaultValueSelect;
  let subtractionTextColon = preDelayColon;

  $: subtractionText = setSubtractionText(subtractionTextColon);

  const child2MarginOnlyLeft = "child-2-margin-only-left-1";
  const marginOnlyLeft = "margin-only-left-1";

  function setSubtractionText(subtractionTextColon) {
    if (subtractionTextColon === preDelayColon) {
      return reverb.preDelay;
    } else {
      return reverb.decay;
    }
  }

  function addColon(string) {
    return `${string}:`;
  }
</script>

<div>
  <LabeledNumberInput labelText={"Tempo in BPM:"} bind:value={tempo} />
  <LabeledRadioGroup
    labelText={"Calculate in ms:"}
    bind:value={durationResult}
    {textValueCombinations}
  />

  <div class="display-flex padding border-bottom">
    {#if durationResult === arithmeticOperation.addition}
      <OptionalLabeledTextSelect
        labelText={preDelayColon}
        bind:value={valueOne}
        values={durations}
        className={child2MarginOnlyLeft}
      />
      <p class={marginOnlyLeft}>+</p>
      <OptionalLabeledTextSelect
        labelText={decayColon}
        bind:value={valueTwo}
        values={durations}
        className={`${child2MarginOnlyLeft} ${marginOnlyLeft}`}
      />
    {:else}
      <OptionalLabeledTextSelect
        labelText={totalReverbColon}
        bind:value={valueOne}
        values={durations}
        className={child2MarginOnlyLeft}
      />
      <p class={marginOnlyLeft}>-</p>
      <OptionalLabeledTextSelect
        bind:value={subtractionTextColon}
        {values}
        className={marginOnlyLeft}
      />
      <OptionalLabeledTextSelect
        bind:value={valueTwo}
        values={durations}
        className={marginOnlyLeft}
      />
    {/if}
  </div>

  <ReverbCalculator
    calculatorOperation={durationResult}
    {tempo}
    {valueOne}
    {valueTwo}
    {subtractionText}
  />
</div>
