// React/music-calculators/src/components/LabeledTextSelect.js
import React from "react";
import TextSelect from "./TextSelect.js";

class LabeledTextSelect extends React.Component {
  constructor(props) {
    super(props);

    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(value) {
    this.props.onChange(value);
  }

  render() {
    return (
      <label className={this.props.class}>
        {this.props.labelText}
        <TextSelect
          values={this.props.values}
          value={this.props.value}
          onChange={this.handleChange}
        />
      </label>
    );
  }
}

export default LabeledTextSelect;

// Lit/src/components/LabeledTextSelect.js
import {LitElement, html} from 'lit';
import dispatchEventValue from '../helpers/customEvent.helpers.js';
import './TextSelect.js';

class LabeledTextSelect extends LitElement {
  static get properties() {
    return {
      className: {type: String},
      labelText: {type: String},
      values: {type: Array},
      value: {type: String},
    };
  }

  constructor() {
    super();
  }

  handleChange(e) {
    dispatchEventValue(this, e.detail);
  }

  render() {
    return html`
      <label .className=${this.className}>
        ${this.labelText}
        <text-select
          .values=${this.values}
          .value=${this.value}
          @value=${this.handleChange}
        /></text-select>
      </label>
    `;
  }
}

customElements.define('labeled-text-select', LabeledTextSelect);
