// Svelte/src/lib/components/LabeledRadioGroup.svelte
<script>
  import RadioGroup from "./RadioGroup.svelte";

  export let labelText;
  export let textValueCombinations;
  export let value;
</script>

<div class="display-block padding border-bottom">
  <p class="text-before-list">{labelText}</p>
  <RadioGroup {textValueCombinations} bind:value />
</div>

// React/music-calculators/src/components/LabeledRadioGroup.js
import React from "react";

import RadioGroup from "./RadioGroup.js";

class LabeledRadioGroup extends React.Component {
  constructor(props) {
    super(props);

    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(value) {
    this.props.onChange(value);
  }

  render() {
    return (
      <div className={"display-block padding border-bottom"}>
        <p className={"text-before-list"}>{this.props.labelText}</p>
        <RadioGroup
          textValueCombinations={this.props.textValueCombinations}
          value={this.props.value}
          onChange={this.handleChange}
        />
      </div>
    );
  }
}

export default LabeledRadioGroup;
