// Lit/src/components/TextSelect.js
import {LitElement, html} from 'lit-element';

import app from '../constants/app.constants.js'; // TODO:

class TextSelect extends LitElement {
  static get properties() {
    return {
      value: {type: String},
      values: {type: Array},
    };
  }

  constructor() {
    super();
  }

  handleChange(e) {
    // e.preventDefault(); TODO: is needed?
  }

  render() {
    // TODO:
    const options = this.values.map(
      (x) => html`<option value=${x}>${x}</option>`
    );
    return html`
      <select .value=${this.value} @change=${this.handleChange}>
        ${options}
      </select>
    `;
  }
}

customElements.define('text-select', TextSelect);

// React/music-calculators/src/components/TextSelect.js
import React from "react";

import app from "../constants/app.constants.js";

class TextSelect extends React.Component {
  constructor(props) {
    super(props);

    this.value = this.props.defaultValue
      ? this.props.defaultValue
      : app.emptyString;

    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(e) {
    e.preventDefault();

    this.value = e.target.value;
    this.props.onChange(this.value);
  }

  render() {
    const options = this.props.values.map((x) => (
      <option key={x} value={x}>
        {x}
      </option>
    ));

    return (
      <select value={this.value} onChange={this.handleChange}>
        {options}
      </select>
    );
  }
}

export default TextSelect;
